#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  local nm_swarm_type=
  if [[ -n "${1:-}" ]]; then
    nm_swarm_type="$1"; shift
  fi

  limbo swarm "${nm_swarm_type:-node}" --swarm-master "$@"
}

source sub "$BASH_SOURCE" "$@"
