#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  "$BASEBOX_INSTANCE" docker machine rm -f "$BASEBOX_INSTANCE"

  ssh-keygen -R "$BASEBOX_IP"
  ssh -o StrictHostKeyChecking=no ubuntu@"$BASEBOX_IP" sudo rm -fv /etc/docker/key.json || true
  ssh -o StrictHostKeyChecking=no ubuntu@"$BASEBOX_IP" sudo docker rm -f swarm-agent-master 2>/dev/null || true
  ssh -o StrictHostKeyChecking=no ubuntu@"$BASEBOX_IP" sudo docker rm -f swarm-agent 2>/dev/null || true
  ssh -o StrictHostKeyChecking=no ubuntu@"$BASEBOX_IP" sudo service docker stop || true
  ssh -o StrictHostKeyChecking=no ubuntu@"$BASEBOX_IP" sudo service docker start || true
  
  local ip_consul="${CACHE_VIP}"

  "$BASEBOX_INSTANCE" docker machine create --driver generic --generic-ip-address "$BASEBOX_IP" --generic-ssh-user ubuntu \
    --swarm \
    --swarm-discovery="consul://${ip_consul}:8500" \
    --engine-storage-driver="zfs" \
    --engine-opt="cluster-store=consul://${ip_consul}:8500" \
    --engine-opt="bip=${BASEBOX_DOCKER_NETWORK_PREFIX}.1/24" \
    --engine-opt="cluster-advertise=eth0:2376" \
    "$@" \
    "$BASEBOX_INSTANCE"
}

source sub "$BASH_SOURCE" "$@"
