#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  eval $(docker machine env --swarm --no-proxy $BASEBOX_INSTANCE)

  if [[ "$#" == 0 ]]; then
    set -- "${BASEBOX_NAME}:vagrant"
  fi
  
  exec docker run --rm -ti -u ubuntu -w /home/ubuntu --net "${BASEBOX_NAME}" "$@" bash -il
}

source sub "$BASH_SOURCE" "$@"
