#!/usr/bin/env bash

function lxc {
  limbo lxc "$@"
}

function main {
  local shome="${_limbo_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  set -x

	lxc launch xenial docker -p default -p docker -p limbo -c boot.autostart=true -c security.nesting=true -c security.privileged=true || true
  cat "$BLOCK_PATH/limbo/.ssh/ssh-vagrant.pub" | "$BASEBOX_INSTANCE" lxc exec docker -- sudo su - ubuntu bash -c 'cd; mkdir -p .ssh; tee .ssh/authorized_keys'
  echo "Acquire::http::Proxy \"http://$CACHE_VIP:3128\";" | lxc exec docker -- tee /etc/apt/apt.conf.d/99boxcache

	lxc exec docker -- touch /root/.cloud-init.hostname
	lxc exec docker -- rm -rf /var/lib/cloud/instance
	lxc exec docker -- cloud-init init
	lxc exec docker -- rm -rf /var/lib/cloud/instance
	lxc exec docker -- cloud-init init

  local ip_lxd="$("$BASEBOX_INSTANCE" lxc info docker | egrep 'eth0:\tinet\t' | awk '{print $3}')"
  ssh-keygen -R "$ip_lxd"

	echo "DOCKER_OPTS='-H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver overlay --bip ${BASEBOX_DOCKER_NETWORK_PREFIX}.1/24'" | lxc exec docker -- tee /etc/default/docker
	lxc exec docker -- env DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install -y docker.io
  ssh -o StrictHostKeyChecking=no ubuntu@"$ip_lxd" sudo service docker stop || true
  ssh -o StrictHostKeyChecking=no ubuntu@"$ip_lxd" sudo service docker start || true

  #ssh -o StrictHostKeyChecking=no ubuntu@"$ip_lxd" sudo rm -fv /etc/docker/key.json || true
  docker machine create --driver generic --generic-ip-address "$ip_lxd" --generic-ssh-user ubuntu \
    --engine-install-url="" \
    --engine-storage-driver="overlay" \
    --engine-opt="bip=${BASEBOX_DOCKER_NETWORK_PREFIX}.1/24" \
    --engine-opt="insecure-registry=172.28.130.2:5000" \
    "$@" \
    "$BASEBOX_INSTANCE"
	lxc restart docker
}

source sub "$BASH_SOURCE" "$@"
