#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  eval $(docker machine env --swarm --no-proxy $BASEBOX_INSTANCE)

  case "${1:-}" in
    *:*)
      exec docker run --rm -i -u ubuntu -w /home/ubuntu "$@"
      ;;
    *)
      exec docker run --rm -i -u ubuntu -w /home/ubuntu --net "${BASEBOX_NAME}" "${BASEBOX_NAME}:vagrant" "$@"
      ;;
  esac
}

source sub "$BASH_SOURCE" "$@"
