#!/usr/bin/env bash

function main {
  local shome="${_limbo_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  eval $(docker machine env --swarm --no-proxy $BASEBOX_INSTANCE)

  exec docker run --rm -ti -u ubuntu -w /home/ubuntu "$@" bash -il
}

source sub "$BASH_SOURCE" "$@"
