#!/usr/bin/env bash

export MACHINE_STORAGE_PATH="${CACHE_DIR}/.docker/machine" 
export VAGRANT_DEFAULT_PROVIDER='docker'

function main {
  local shome="${_limbo_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  eval $(docker machine env --swarm --no-proxy $BASEBOX_INSTANCE)

  exec docker "$@"
}

source sub "$BASH_SOURCE" "$@"
