#!/usr/bin/env bash
  
function _limbo_swarm_profile {
  local shome="${_limbo_swarm_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/exec:$PATH"

  export LIMBO_HOME="$shome"
}

_limbo_swarm_profile
